#ifndef EXECUTION_RESULT_H_
#define EXECUTION_RESULT_H_

enum executionResultEnum
{
	EXECUTION_RESULT_OK,

	EXECUTION_RESULT_FAILED_TO_START_WINSOCK,
	EXECUTION_RESULT_WRONG_WINSOCK_VERSION,
	EXECUTION_RESULT_INVALID_SOCKET,
	EXECUTION_RESULT_BINDING_ERROR,
	EXECUTION_RESULT_CONNECTION_TO_SERVER_FAILED,
	EXECUTION_RESULT_FAILED_TO_ACCEPT_CONNECTION
	//EXECUTION_RESULT_
};

#endif