#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_

#define	INCORRECT_INPUT_PARAMS				10
#define INPUT_RASTER_DOES_NOT_EXIST			11
#define WRONG_EXTENT						12
#define	FILE_NOT_OPEN						13
#define FLOAT_TO_RASTER_CONVERSION_ERROR	14
#define RASTER_TO_FLOAT_CONVERSION_ERROR	15
#define ARRAY_INDEX_OUT_OF_BOUNDS			16
#define MEMORY_ALREADY_ALLOCATED			17
#define WRONG_CSV_FILE						18

#define OTHER_ERROR							99


#endif