#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_

#define	INCORRECT_INPUT_PARAMS				10
#define WRONG_EXTENT						11
#define	FILE_NOT_OPEN						12
#define FLOAT_TO_RASTER_CONVERSION_ERROR	13
#define RASTER_TO_FLOAT_CONVERSION_ERROR	14

#define OTHER_ERROR							99


#endif